// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {attachments} from '../models';
import {context} from '../models';

export function GetAttachmentDataURL(arg1:string,arg2:string):Promise<string>;

export function PickImages():Promise<Array<attachments.PickedImage>>;

export function SetAppContext(arg1:context.Context):Promise<void>;

export function UploadAttachment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<attachments.UploadResult>;
