// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAttachmentDataURL(arg1, arg2) {
  return window['go']['attachments']['Service']['GetAttachmentDataURL'](arg1, arg2);
}

export function PickImages() {
  return window['go']['attachments']['Service']['PickImages']();
}

export function SetAppContext(arg1) {
  return window['go']['attachments']['Service']['SetAppContext'](arg1);
}

export function UploadAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['attachments']['Service']['UploadAttachment'](arg1, arg2, arg3, arg4);
}
